include:
  - project: "the-microservice-dungeon/devops-team/common-ci-cd"
    ref: "main"
    file:
      - "helm/package-publish.yaml"
      - "container/image-dockerfile-publish.yaml"

stages: # TODO add needed Stages like test, build and so on
  - lint
  - test
  - build_container_push
  - helm

variables:
  PATH_TO_CHART: "helm-chart"
  # TODO Change Player-Name to your Player
  CHART_NAME: "player-swagkingthethird"
  # TODO Change Image name to Player-Name (end of line)
  CI_MSD_CONTAINER_REGISTRY: "registry.gitlab.com/the-microservice-dungeon/devops-team/msd-image-registry/player-swagkingthethird"



lint:
  stage: lint
  image: node:latest
  cache:
    paths:
      - node_modules/
  before_script:
    - npm ci
  script:
    - npm run lint
  allow_failure: true

test:
  stage: test
  image: node:latest
  cache:
    paths:
      - node_modules/
  before_script:
    - npm ci
  script:
    - npm run test

# build stage use this, to build docker image from dockerfile and push it to our container registry
container-image-publish:
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: always

helm-package-publish:
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      changes:
        - ${PATH_TO_CHART}/**/*
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: always

